name: keycloak build matrix

on:
  schedule:
    - cron: '47 3 * * 1'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # spefify the java distribution to use
  JAVA_DIST: adopt

jobs:
  build:

    runs-on: ubuntu-latest
    
    continue-on-error: true
    
    strategy:
      fail-fast: false
      matrix:
        # specify the keycloak version to use
        KC_VERSION: [15.1.1, 16.1.0]
        # specify the java version to use
        JAVA_VERSION: [11]

    steps:

      - name: repo checkout keycloak
        uses: actions/checkout@v2
        with:
          repository: keycloak/keycloak
          ref: ${{ matrix.KC_VERSION }}
          path: keycloak

      - name: repo checkout keycloak-extension-playground
        uses: actions/checkout@v2
        with:
          repository: thomasdarimont/keycloak-extension-playground
          path: keycloak-extension-playground

      - name: java setup
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}

      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: maven configure
        uses: s4u/maven-settings-action@v2.4.1
        with:
          mirrors: '[{"id": "maven-default-http-blocker", "name": "Dummy mirror to override default blocking mirror that blocks http", "mirrorOf": "dummy", "url": "http://0.0.0.0/"}]'

      - name: build keycloak
        run: mvn -q --batch-mode clean install -DskipTests
        working-directory: keycloak
      
      - name: build keycloak-extension-playground
        run: |
          sed -i "s|<keycloak.version>.*</keycloak.version>|<keycloak.version>${{ matrix.KC_VERSION }}</keycloak.version>|g" pom.xml
          mvn -q --batch-mode clean package
          rm keycloak-playground-server/target/*.jar
        working-directory: keycloak-extension-playground

      - name: release files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: keycloak-${{ matrix.KC_VERSION }}-jdk-${{ matrix.JAVA_VERSION }}-${{ env.JAVA_DIST }}
          files: keycloak-extension-playground/**/target/*.jar

      - name: Remove keycloak artifacts before caching
        if: steps.cache.outputs.cache-hit != 'true'
        run: rm -rf ~/.m2/repository/org/keycloak
